name: Publish as npm module

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: https://registry.npmjs.org/

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install
        run: npm install

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
